### ISSUE TITLE
Игнор работает как-то странно...

### ISSUE THREAD

**Issue by Philoceratops** [ImaginariaRU/RPGLinks#12]
На данный момент убрать человека из игнора нельзя. Пишет, что настройки обновлены - ничего не происходит. То, есть, вечная ненависть максимализм и всё такое, но неплохо было бы иметь возможность делать откаты в принципе. 

Комментарий (не обязательно) - это не скрытый комментарий, для заигнорившего, а публичный. 

Написать туда можно что угодно, отредактировать нельзя и видят это все (непонятно зачем) - неплохо бы, чтобы это можно было редактировать и было бы написано в меню игнорирования, что комментарий публичный. 

Война войной, но я хочу иметь возможность просто не видеть людей и прекратить конфликт, а не рассказывать всем всё, что я о них думал в момент нажатия на кнопку "игнор".

**Comment by Philoceratops** [comment]
Есть прогресс?

**Comment by KarelWintersky** [comment]
Нет

**Comment by Philoceratops** [comment]
Есть надежды на прогресс?

**Comment by KarelWintersky** [comment]
https://github.com/ImaginariaRU/dear-imaginaria/issues
