### ISSUE TITLE
Запрос на обновление инфо

### ISSUE THREAD

**Issue by wymrc** [ImaginariaRU/RPGLinks#18]
Обновите, пожалуйста, информацию и ссылки. "[Санкт-Петербург] DnD в Playloft GaGa + чат в Telegram" - клуб уже некоторое время называется "Клуб Day20 в Плейлофте GaGa", ссылка теперь https://vk.com/day20rpg. Чат в телеграмме - t.me/day20rpg.

**Comment by KarelWintersky** [comment]
fixed
